apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-events
    targetRevision: "*"
    helm:
      values: |
        crds:
          install: true
          keep: true
        nameOverride: argo-events
        controller:
          replicas: 2
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              namespace: argo-events
              interval: 30s
              labels:
                release: kube-prometheus-stack
        eventsourceController:
          replicas: 2
        sensorController:
          replicas: 2
        eventbusController:
          replicas: 2
        createAggregateRoles: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events-event-bus
  namespace: argocd
spec:
  destination:
    namespace: argo-events
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/argo-events
    repoURL: https://github.com/coil398/home-k8s
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
