apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: code-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/coder/code-server
    path: ci/helm-chart
    targetRevision: main
    helm:
      values: |
        replicaCount: 1
        service:
          type: ClusterIP
          port: 8080
          targetPort: 8080
        ingress:
          enabled: false
        persistence:
          enabled: true
          size: 100Gi
          storageClass: "longhorn-r2"
          accessMode: ReadWriteOnce
        extraArgs:
          - --auth
          - none
          - --disable-telemetry
          - --bind-addr
          - 0.0.0.0:8080
        securityContext:
          privileged: true
          runAsUser: 0
        extraVars:
          - name: DOCKER_TLS_CERTDIR
            value: ""
          - name: DOCKER_HOST
            value: unix:///var/run/docker.sock
