apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: code-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/coder/code-server
    path: ci/helm-chart
    targetRevision: main
    helm:
      values: |
        replicaCount: 1
        auth:
          enabled: false
        service:
          type: ClusterIP
          port: 8080
          targetPort: 8080
        ingress:
          enabled: false
        persistence:
          enabled: true
          size: 10Gi
          storageClass: "longhorn-r2"
          accessMode: ReadWriteOnce
