apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: code-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/coder/code-server
    path: ci/helm-chart
    targetRevision: main
    helm:
      values: |
        replicaCount: 1
        service:
          type: ClusterIP
          port: 8080
          targetPort: 80
        ingress:
          enabled: false
        persistence:
          enabled: true
          size: 100Gi
          storageClass: "longhorn-r2"
          accessMode: ReadWriteOnce
        extraArgs:
          - --auth
          - none
          - --disable-telemetry
          - --bind-addr
          - 0.0.0.0:8080
        securityContext:
          runAsUser: 0
        extraVars:
          - name: DOCKER_TLS_CERTDIR
            value: ""
          - name: DOCKER_HOST
            value: unix:///var/run/docker.sock
          - name: DOCKER_DATA_ROOT
            value: /var/lib/docker
        extraVolumeMounts:
          - name: docker-data
            mountPath: /var/lib/docker
            existingClaim: shared-docker-data
        extraContainers: |
          - name: security-proxy
            image: nginx:alpine
            ports:
              - containerPort: 80
                name: http
            volumeMounts:
              - name: nginx-config
                mountPath: /etc/nginx/nginx.conf
                subPath: nginx.conf
        extraConfigmapMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            configMap: security-proxy-config
            subPath: nginx.conf
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server-ingress
  namespace: argocd
spec:
  destination:
    namespace: code-server
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/code-server
    repoURL: https://github.com/coil398/home-k8s
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

