apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: "*"
    helm:
      values: |
        rbac:
          create: true
        serviceAccount:
          create: true
          name: alloy
        clusterRole:
          create: true
          rules:
            - apiGroups: [""]
              resources: ["pods", "pods/log", "nodes", "services", "endpoints", "namespaces"]
              verbs: ["get", "list", "watch"]
            - apiGroups: [""]
              resources: ["configmaps", "secrets"]
              verbs: ["get", "list", "watch"]
            - apiGroups: ["apps"]
              resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
              verbs: ["get", "list", "watch"]
            - apiGroups: ["monitoring.coreos.com"]
              resources: ["prometheusrules"]
              verbs: ["get", "list", "watch"]
        controller:
          type: daemonset
        alloy:
          configMap:
            content: |
              discovery.kubernetes "pods" {
                role = "pod"
              }
              loki.source.kubernetes "pods" {
                targets = discovery.kubernetes.pods.targets
                forward_to = [loki.write.default.receiver]
                clustering {
                  enabled = true
                }
              }
              loki.write "default" {
                endpoint {
                  url = "http://loki-gateway/loki/api/v1/push"
                }
              }
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
