apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: jupyterhub
    targetRevision: "*"
    helm:
      values: |
        hub:
          configuration: |
            hub:
              config:
                JupyterHub:
                  admin_access: true
                  authenticator_class: jupyterhub.auth.NullAuthenticator
                Authenticator:
                  auto_login: true
        proxy:
          service:
            type: ClusterIP
            port: 80
        singuleuser:
          imagePuller:
            enabled: false
          extraEnvVars:
            - name: JUPYTER_ENABLE_LAB
              value: "yes"
            - name: PIP_CACHE_DIR
              value: "/home/jovyan/.pip-cache"
        postgresql:
          enabled: false
        externalDatabase:
          host: postgres-postgresql-ha-pgpool.postgres.svc.cluster.local
          port: 5432
          user: postgres
          database: jupyterhub
          existingSecret: ""
          password: postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: jupyter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
