apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/coil398/home-k8s
    path: manifests/jupyterlab
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: jupyter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
