apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyterlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://hub.jupyter.org/helm-chart/
    chart: jupyterhub
    targetRevision: "*"
    helm:
      values: |
        hub:
          config:
            JupyterHub:
              authenticator_class: dummy
            DummyAuthenticator:
              password: ""
            Authenticator:
              allow_all: true
          db:
            type: postgres
            url: postgres://postgres:postgres@postgres-postgresql-ha-pgpool.postgres.cluster.local:5432/jupyterhub
        proxy:
          secretToken: ""
          service:
            type: ClusterIP
            ports:
              http: 80
        singleuser:
          defaultUrl: "/lab"
          extraEnv:
            JUPYTER_ENABLE_LAB: "yes"
            PIP_CACHE_DIR: "/home/jovyan/.pip-cache"
          storage:
            capacity: 500Gi
            dynamic:
              storageClass: "longhorn-r2"
        prePuller:
          hook:
            enabled: false
          continuous:
            enabled: false
        postgresql:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: jupyter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
