apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "*"
    helm:
      values: |
        grafana:
          adminPassword: password
          service:
            type: ClusterIP
          persistence:
            enabled: true
            size: 10Gi
            storageClassName: longhorn-r2
          grafana.ini:
            server:
              root_url: https://grafana.coil398.io/
              serve_from_sub_path: false
              protocol: http
              http_port: 3000
              domain: grafana.coil398.io
            security:
              allow_embedding: true

        prometheus:
          prometheusSpec:
            retention: 30d
            retentionSize: 50GB
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  storageClassName: longhorn-r2
                  resources:
                    requests:
                      storage: 100Gi

        alertmanager:
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  storageClassName: longhorn-r2
                  resources:
                    requests:
                      storage: 10Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
