apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "*"
    helm:
      values: |
        deploymentMode: SimpleScalable
        minio:
          enabled: false
        loki:
          commonConfig:
            replication_factor: 2
          storage:
            type: s3
            bucketNames:
              chunks: loki-chunks
              ruler: loki-ruler
              admin: loki-admin
            s3:
              endpoint: http://minio.minio.svc.cluster.local:9000
              region: us-east-1
              accessKeyId: admin
              secretAccessKey: password
              s3ForcePathStyle: true
              insecure: true
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: s3
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          limits_config:
            retention_period: 30d
          compactor:
            retention_enabled: true
            retention_delete_delay: 2h
            retention_delete_worker_count: 150
            compaction_interval: 10m
            delete_request_store: s3
        write:
          replicas: 2
          persistence:
            enabled: true
            size: 100Gi
        read:
          replicas: 2
          persistence:
            enabled: true
            size: 100Gi
        backend:
          replicas: 2
          persistence:
            enabled: true
            size: 100Gi
        serviceMonitor:
          enabled: true
          labels:
            release: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
