apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "*"
    helm:
      values: |
        deploymentMode: SimpleScalable
        loki:
          commandConfig:
            replication_factor: 2
          limits_config:
            retention_period: 30d
            max_global_streams_per_user: 10000
            ingestion_rate_mb: 16
            ingestion_burst_size_mb: 32
          compactor:
            working_directory: /tmp/loki/boltdb-shipper-compactor
            shared_store: filesystem
            compaction_interval: 10m
            retention_enabled: true
            retention_delete_delay: 2h
            retention_delete_worker_count: 150
          write:
            replicas: 2
            persistence:
              enabled: true
              size: 100Gi
          read:
            replicas: 2
            persistence:
              enabled: true
              size: 100Gi
          backend:
            replicas: 2
            persistence:
              enabled: true
              size: 100Gi
          serviceMonitor:
            enabled: true
            labels:
              release: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
