apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: nginx
spec:
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/nginx
    repoURL: https://github.com/coil398/home-k8s
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
