apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: postgresql-ha
    targetRevision: 16.0.11
    helm:
      values: |
        persistence:
          enabled: true
          storageClass: longhorn-r2
          size: 500Gi
        postgresql:
          username: postgres
          password: postgres
          database: db
          replicaCount: 2
        pgpool:
          enabled: true
          replicaCount: 1
          adminUsername: admin
          adminPassword: postgres
        volumePermissions:
          enabled: true
