apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: postgresql-ha
    targetRevision: "*"
    helm:
      values: |
        persistence:
          enabled: true
          storageClass: longhorn-r2
          size: 500Gi
        postgresql:
          username: postgres
          password: postgres
          database: db
          replicaCount: 2
          repmgrUsername: repmgr
          repmgrPassword: repmgr
          repmgrDatabase: repmgr
        pgpool:
          enabled: true
          replicaCount: 2
          adminUsername: admin
          adminPassword: postgres
          useLoadBalancing: true
          disableLoadBalancingOnWrite: "transaction"
          srCheckUsername: repmgr
          srCheckPassword: repmgr
        volumePermissions:
          enabled: true
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
            interval: 30s
            labels:
              release: kube-prometheus-stack
          service:
            annotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: "9187"
