apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://seaweedfs.github.io/seaweedfs/helm
    chart: seaweedfs
    targetRevision: "*"
    helm:
      values: |
        # Global settings
        global:
          registry: ""
          repository: ""
          imageName: chrislusf/seaweedfs
          imagePullPolicy: IfNotPresent
          imagePullSecrets: ""
          restartPolicy: Always
          loggingLevel: 1
          enableSecurity: false
          serviceAccountName: "seaweedfs"
          automountServiceAccountToken: true
          # Security contexts
          podSecurityContext:
            enabled: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
          containerSecurityContext:
            enabled: true
            runAsUser: 1000
            allowPrivilegeEscalation: false

        master:
          enabled: true
          repository: null
          imageName: null
          imageTag: null
          restartPolicy: null
          replicas: 3
          port: 9333
          grpcPort: 19333
          ipBind: "0.0.0.0"
          volumePreallocate: false

          # Master configuration
          config: |
            # Add any specific master config here

          # Persistence for master metadata
          data:
            type: "persistentVolumeClaim"
            size: "10Gi"
            storageClass: "nfs-rwx"

          # Logs
          logs:
            type: "persistentVolumeClaim"
            size: "2Gi"
            storageClass: "nfs-rwx"

          service:
            type: "ClusterIP"

          # Resource limits
          resources: {}
          nodeSelector: {}
          tolerations: []
          affinity: ""
          volumeSizeLimitMB: 30000

        volume:
          enabled: true
          repository: null
          imageName: null
          imageTag: null
          restartPolicy: null
          replicas: 2
          port: 8080
          grpcPort: 18080
          ipBind: "0.0.0.0"

          # Data persistence
          dataDirs:
            - name: data1
              type: "persistentVolumeClaim"
              size: "1000Gi"
              storageClass: "nfs-rwx"
              maxVolumes: 50

          logs:
            type: "persistentVolumeClaim"
            size: "2Gi"
            storageClass: "nfs-rwx"

          service:
            type: "ClusterIP"

          resources: {}
          nodeSelector: {}
          tolerations: []
          affinity: ""

        filer:
          enabled: true
          repository: null
          imageName: null
          imageTag: null
          restartPolicy: null
          replicas: 2
          port: 8888
          grpcPort: 18888

          config: |
            [leveldb2]
            # local on disk, mostly for simple single-machine setup, fairly scalable
            # faster than previous leveldb, recommended.
            enabled = true
            dir = "/data/filerldb2"

          s3:
            enabled: true
            port: 8333
            httpsPort: 0
            allowEmptyFolder: true
            domainName: ""
            enableAuth: false

          # Data persistence
          data:
            type: "persistentVolumeClaim"
            size: "10Gi"
            storageClass: "nfs-rwx"

          # Logs
          logs:
            type: "persistentVolumeClaim" 
            size: "2Gi"
            storageClass: "nfs-rwx"

          service:
            type: "ClusterIP"

          # Resource limits
          resources: {}
          nodeSelector: {}
          tolerations: []
          affinity: ""

        ingress:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: seaweedfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs-service
  namespace: argocd
spec:
  destination:
    namespace: seaweedfs
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/seaweedfs
    repoURL: https://github.com/coil398/home-k8s
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
