apiVersion: v1
kind: Service
metadata:
  name: master-cloudflared
  namespace: default
spec:
  clusterIP: None
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: master-cloudflared
  namespace: default
subsets:
  - addresses:
      - ip: 172.28.6.100
    ports:
      - port: 443
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-access
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: external-access
    namespace: kube-system
