apiVersion: v1
kind: ConfigMap
metadata:
  name: security-proxy-config
  namespace: code-server
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        upstream code-server {
            server 127.0.0.1:8080;
        }

        server {
            listen 80;
            server_name _;

            # セキュリティヘッダーの追加
            add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self' ws: wss:; frame-src 'self'; object-src 'none'; base-uri 'self';" always;
            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header X-XSS-Protection "1; mode=block" always;
            add_header Referrer-Policy "strict-origin-when-cross-origin" always;

            # WebSocket対応
            location / {
                proxy_pass http://code-server;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                # WebSocketタイムアウト設定
                proxy_read_timeout 86400;
            }
        }
    }
