apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-filer-vip
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: seaweedfs
    app.kubernetes.io/instance: seaweedfs
    app.kubernetes.io/component: filer
  ports:
    - name: http
      port: 8888
      targetPort: 8888
