apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterlab
  labels:
    app: jupyterlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterlab
  template:
    metadata:
      labels:
        app: jupyterlab
    spec:
      securityContext:
        fsGroup: 100
      initContainers:
        - name: fix-permissions
          image: jupyter/datascience-notebook:latest
          command:
            [
              "sh",
              "-c",
              "chown -R 1000:100 /home/jovyan/work /home/jovyan/.jupyter /home/jovyan/.bashrc && chmod -R 755 /home/jovyan/work /home/jovyan/.jupyter /home/jovyan/.bashrc",
            ]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: workspace
              mountPath: /home/jovyan/work
            - name: jupyter-config
              mountPath: /home/jovyan/.jupyter
            - name: jupyter-bashrc
              mountPath: /home/jovyan/.bashrc
      containers:
        - name: jupyterlab
          image: jupyter/datascience-notebook:latest
          ports:
            - containerPort: 8888
              name: jupyter
          command: ["jupyter"]
          args:
            - lab
            - --ip=0.0.0.0
            - --port=8888
            - --no-browser
            - --allow-root
            - --NotebookApp.token=''
            - --NotebookApp.password=''
            - --NotebookApp.disable_check_xsrf=True
            - --NotebookApp.allow_origin='*'
            - --NotebookApp.allow_remote_access=True
          env:
            - name: JUPYTER_ENABLE_LAB
              value: "yes"
            - name: GRANT_SUDO
              value: "yes"
            - name: CHOWN_HOME
              value: "yes"
            - name: CHOWN_HOME_OPTS
              value: "-R"
            - name: NB_USER
              value: "jovyan"
            - name: NB_UID
              value: "1000"
            - name: NB_GID
              value: "100"
          volumeMounts:
            - name: workspace
              mountPath: /home/jovyan/work
            - name: jupyter-config
              mountPath: /home/jovyan/.jupyter
            - name: jupyter-bashrc
              mountPath: /home/jovyan/.bashrc
          livenessProbe:
            httpGet:
              path: /lab/api/status
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /lab/api/status
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: jupyterlab-workspace
        - name: jupyter-config
          persistentVolumeClaim:
            claimName: jupyterlab-config
        - name: jupyter-bashrc
          persistentVolumeClaim:
            claimName: jupyterlab-bashrc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterlab-workspace
  namespace: jupyter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: longhorn-r2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterlab-config
  namespace: jupyter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn-r2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterlab-bashrc
  namespace: jupyter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn-r2
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterlab
  namespace: jupyter
  labels:
    app: jupyterlab
spec:
  selector:
    app: jupyterlab
  ports:
    - port: 8888
      targetPort: 8888
      name: jupyter
      protocol: TCP
  type: ClusterIP
